#define INA_REG_ADDR_CONFIG			0x00
#define INA_REG_ADDR_SHUNT_VOLTAGE	0x01
#define INA_REG_ADDR_BUS_VOLTAGE	0x02
#define INA_REG_ADDR_POWER			0x03
#define INA_REG_ADDR_CURRENT		0x04
#define INA_REG_ADDR_CALIBRATION	0x05

#define INA_SLAVE_ADDR	0b1000000

void ina_init(void);
